num_workers: 6
device: "cuda:0"
emb_path: "/home/sduarte/data/IDPfun2/embeddings/" 
data_path: "/home/sduarte/data/IDPfun2/dataset/" 
# data_path: "/home/data/IDPfun2/MobiDB/datasets/redundant_without_observed/" 
# [ ]: delete this file!! is not used anymore